#############################
### PROJECT CONFIGURATION ###
#############################

####################
# Sample table info
####################

sample_table: 'input/Sample_sheet.csv'

####################
# Directories
####################
input_dir: 'input/'
fastq_dir: 'input/fastq/'
input_genome: 'input/genome_files/'
output_dir: 'output/'
temp_dir: 'temp/'
temp_fastq: 'temp/fastq/'
temp_bam: 'temp/bam/'
qc_temp: 'temp/quality_control/'
temp_index: 'temp/index/'
log_dir: 'logs/'
envs_dir: 'envs/'


####################
# Analysis options
####################



binned_coverage:
  bin_size: 200
  which_strand: 'both'
  # 'both', 'plus', 'minus', 'none'
trim_fastq:
  min_read_length: 25 # Default 25
  min_read_quality: 20 # Default 20
  special_adapters:
    bool: False # Default True (True: Adapters auto-detected; False: special adapters (adapter_1 & adapter_2)
    adapter_1: 'AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC'
    adapter_2: 'GATCGTCGGACTGTAGAACTCTGAACGTGTAGATCTCGGTGGTCGCCGTATCATT'
bowtie1:
  indexing:
    download_link: 'NA'
    fasta_file: 'Homo_sapiens.GRCh38.dna.primary_assembly.IVT_snoRD_lib_templates.fa.gz'
  align:
    mismatches_max: '10' # Default 2, max 3 for Bowtie1, unlimited for STAR
    n_multi_mappers: '100' # No multimappers: 1, Allow multimappers: >1 ~100
star:
  indexing:
    download_link:
      fasta: 'NA'
      gtf: 'NA'
    fasta_file: 'Homo_sapiens.GRCh38.dna.primary_assembly.IVT_snoRD_lib_templates.fa.gz'
    gtf_file: 'Homo_sapiens.GRCh38.108.IVT.snoRD.lib.gtf.gz'
  align:
    mismatches_max: '10' # Default 2, (max 3 in Bowtie1)
    n_multi_mappers: '100' # No multimappers: 1, Allow multimappers: >1 ~100


####################
# SLURM options
####################

slurm:
  binned_coverage:
    threads: 15
    mem: 64G
    runtime: 7h
  bowtie_align:
    threads: 17
    mem: 16G
    runtime: 7h
  bowtie_index:
    threads: 9
    mem: 16G
    runtime: 7h
  trim_fastq:
    threads: 15
    mem: 1G
    runtime: 7h
  star_align:
    threads: 9
    mem: 64G
    runtime: 7h
  star_index:
    threads: 16
    mem: 64G
    runtime: 7h

